name: Build
on:
  push:
    branches: ["main"]
  workflow_dispatch:
env:
  SRC_FILE: ftpdlite.py
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Linting...
        run: |
          pip3 install ruff
          python3 -m ruff check $SRC_FILE
      - name: Compiling bytecode...
        run: |
          pip3 install mpy-cross
          python3 -m mpy_cross $SRC_FILE
      # Hold until --skip-errors is fixed (https://github.com/pdoc3/pdoc/issues/421)
      # - name: Creating class doc...
      #   run: |
      #     pip3 install pdoc3
      #     pdoc3 --force --skip-errors --html --output-dir=docs $SRC_FILE
      - name: Committing changes...
        run: |
          if [ $(git diff | wc -l) -gt 0 ]; then
            git config --global user.name "$GITHUB_REPOSITORY_OWNER"
            git config --global user.email "$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
            git commit -am "GitHub Actions"
            git push
          fi
